gText_Birch_Welcome::
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to the world of POKéMON!\p"
	.string "My name is BIRCH.\p"
	.string "But everyone calls me the POKéMON\n"
	.string "PROFESSOR.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "This world is widely inhabited by\n"
	.string "creatures known as POKéMON.\p"
	.string "We humans live alongside POKéMON,\n"
	.string "at times as friendly playmates, and\l"
	.string "at times as cooperative workmates.\p"
	.string "And sometimes, we band together\n"
	.string "and battle others like us.\p"
	.string "But despite our closeness, we don't\n"
	.string "know everything about POKéMON.\p"
	.string "In fact, there are many, many\n"
	.string "secrets surrounding POKéMON.\p"
	.string "To unravel POKéMON mysteries,\n"
	.string "I've been undertaking research.\l"
	.string "That's what I do.\p"
	.string "$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to my\n"
	.string "hometown of LITTLEROOT.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_BoyOrGirl2::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"




gText_Birch_AndYouAre::
	.string "Welcome to Pokémon Escape Room 2!\p"
	.string " $"

gText_Birch_BoyOrGirl::
	.string "Please choose your character.$"

gText_Birch_WhatsYourName::
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"


gText_Birch_ImportantInfo_part1::
	.string "READ CAREFULLY\p"

    .string "1) The game's mechanics reflect GEN 9\n"
    .string "where possible; overworld mechanics\l"
    .string "are the main exception.\p"

    .string "2) Moves & learnsets are mostly vanilla.\n"
    .string "Move PP may be reduced (e.g. 5 PP Mimic)\l"
    .string "to suit puzzle design.\p"

    .string "3) Battle RNG has been disabled.\n"
    .string "Outcomes are deterministic (0% or 100%)\l"
    .string "with Assist as sole exception.\p"

    .string "4) You won't get softlocked.\n"
    .string "The game has an anti-softlock system\l"
    .string "to undo any mistake you could make.\l"
    .string "This may include side effects (such as\l"
    .string "healing your party) to prevent gaining\l"
    .string "an advantage via the system.\p$"

gText_Birch_ImportantInfo_part2::
    .string "5) There are QOL features to further\n"
    .string "reduce the need for save states:\l"
    .string "- Wild battles can be forfeited.\l"
    .string "- Lost items may return after battle.\l"
    .string "- Pre-damaged states can be restored.\l"
    .string "- Losing far from the respawn lets you\l"
    .string "   warp back to the battle area.\p"
    .string "None of these features are required to\n"
    .string "solve any of the puzzles.\p"

    .string "6) Your party is fully healed each time\n"
    .string "you beat a trainer.\p"

    .string "7) Any Pokémon could have custom IVs or\n"
    .string "EVs, including wild Pokémon.\p"

    .string "8) EXP gain from battling has been\n"
    .string "disabled.\p"

	.string "9) There are no hidden items.\p"

	.string "Your time starts now.\n"
    .string "Good luck!\p$"