gText_Birch_Welcome::
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to the world of POKéMON!\p"
	.string "My name is BIRCH.\p"
	.string "But everyone calls me the POKéMON\n"
	.string "PROFESSOR.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "This world is widely inhabited by\n"
	.string "creatures known as POKéMON.\p"
	.string "We humans live alongside POKéMON,\n"
	.string "at times as friendly playmates, and\l"
	.string "at times as cooperative workmates.\p"
	.string "And sometimes, we band together\n"
	.string "and battle others like us.\p"
	.string "But despite our closeness, we don't\n"
	.string "know everything about POKéMON.\p"
	.string "In fact, there are many, many\n"
	.string "secrets surrounding POKéMON.\p"
	.string "To unravel POKéMON mysteries,\n"
	.string "I've been undertaking research.\l"
	.string "That's what I do.\p"
	.string "$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to my\n"
	.string "hometown of LITTLEROOT.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_BoyOrGirl2::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"




gText_Birch_AndYouAre::
	.string "Welcome to Pokémon Cave Escape!\p"
	.string "In this game you are trapped in a cave\n"
	.string "with the ultimate goal of getting out.\p"
	.string "You'll have to solve puzzles, navigate\n"
	.string "tough battles and come up with clever\l"
	.string "ideas in order to progress.\p"
	.string " $"

gText_Birch_BoyOrGirl::
	.string "Please choose your character.$"

gText_Birch_WhatsYourName::
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_AreYouReady::
	.string "READ CAREFULLY\p"
	.string "1) The game's learnsets and battle\n"
	.string "mechanics are based on GEN 9.\p"
	.string "2) Match tiebreakers will follow\n"
	.string "competitive battling rules.\l"
	.string "This means you could potentially win\l"
	.string "despite losing your final Pokémon.\p"
	.string "3) Battle RNG has been disabled.\n"
	.string "Catch rates, move effects, accuracy,\l"
	.string "and damage are now deterministic.\p"
	.string "4) There is no need for grinding of any\n"
	.string "kind. You don't earn EXP from battles.\p"
	.string "5) Any item you can find on the map\n"
	.string "directly will be inside an item ball.\p"
	.string "6) Trainer battles have a forfeit option\n"
	.string "(Run), which counts as a regular loss.\p"
	.string "7) You won't get softlocked unless you\n"
	.string "toss away items, release Pokémon, or\l"
	.string "REALLY mess up the Strength puzzle.\p"
	.string "8) Try to avoid using speed up.\n"
	.string "You might miss important details like\l"
	.string "NPC dialogue.\p"
	.string "Your time starts now.\n"
	.string "Good luck!\p$"




